### ISSUE TITLE
Error on startup: chown: unknown user root.root

### ISSUE THREAD

**Issue by unmacaque** [Hermsi1337/docker-sshd#14]
Take the following compose file:

```
services:
  sshd:
    image: hermsi/alpine-sshd:9.9_p1-r2
    container_name: sshd
    environment:
      ROOT_KEYPAIR_LOGIN_ENABLED: "true"
    volumes:
      - ./test.pub:/root/.ssh/authorized_keys
```

Since `9.9_p1_r2`, this will now produce an error on startup:

```
sshd  | [INFO] Applying configuration for 'root' user ...
sshd  | [INFO]     password for user 'root' set
sshd  | [WARN]     user 'root' is now UNLOCKED
sshd  | chown: unknown user root.root
sshd exited with code 1
```

The container can be started up again with image tag `9.7_p1-r4`.

I suspect it could possibly be due to syntax of `chown` command. I will create a PR for it.
